import pandas as pd

data = [
    # --- Diabetes ---
    ["diabetes", "banana", "avoid", "High in sugar, raises blood glucose."],
    ["diabetes", "apple", "recommend", "Low GI, high fiber, helps regulate blood sugar."],
    ["diabetes", "rice", "avoid", "Refined carbs, spikes blood sugar."],
    ["diabetes", "brown rice", "recommend", "Lower GI, more fiber than white rice."],
    ["diabetes", "wheat", "avoid", "Refined flour spikes glucose; prefer whole wheat."],
    ["diabetes", "oats", "recommend", "Soluble fiber improves insulin sensitivity."],
    ["diabetes", "spinach", "recommend", "Low carb, magnesium-rich, good for glucose."],
    ["diabetes", "broccoli", "recommend", "Antioxidants support glucose control."],
    ["diabetes", "cabbage", "recommend", "Low calorie, stabilizes blood sugar."],
    ["diabetes", "tomato", "recommend", "Low sugar, antioxidant lycopene helps."],
    ["diabetes", "fish", "recommend", "Omega-3 improves insulin sensitivity."],
    ["diabetes", "chicken", "recommend", "Lean protein helps regulate blood sugar."],
    ["diabetes", "egg", "recommend", "Low carb protein source."],
    ["diabetes", "milk", "avoid", "May spike insulin depending on fat content."],
    ["diabetes", "paneer", "recommend", "Low carb, protein rich, controls hunger."],
    ["diabetes", "cheese", "avoid", "High fat, worsens insulin resistance."],
    ["diabetes", "lentils", "recommend", "Fiber slows glucose release."],
    ["diabetes", "chickpeas", "recommend", "Low GI protein + fiber."],
    ["diabetes", "nuts", "recommend", "Healthy fats improve insulin sensitivity."],
    ["diabetes", "green tea", "recommend", "Polyphenols improve glucose metabolism."],
    ["diabetes", "banana", "avoid", "High in sugar, raises blood glucose."],
    ["diabetes", "apple", "recommend", "Low GI, high fiber, helps regulate blood sugar."],
    ["diabetes", "mango", "avoid", "High sugar, spikes blood glucose."],
    ["diabetes", "papaya", "moderate", "Contains natural sugars; small portions only."],
    ["diabetes", "guava", "recommend", "Low GI, high fiber, helps control sugar."],
    ["diabetes", "orange", "recommend", "Vitamin C rich, low glycemic impact."],
    ["diabetes", "watermelon", "moderate", "High sugar; portion control needed."],
    ["diabetes", "rice", "avoid", "Refined carbs, spikes blood sugar."],
    ["diabetes", "brown rice", "recommend", "Lower GI, more fiber than white rice."],
    ["diabetes", "roti", "recommend", "Whole wheat, low GI, good for glucose control."],
    ["diabetes", "jowar roti", "recommend", "Gluten-free, high fiber, stabilizes sugar."],
    ["diabetes", "bajra roti", "recommend", "Low GI millet; helps blood sugar control."],
    ["diabetes", "poha", "moderate", "Traditional Indian breakfast; portion control needed."],
    ["diabetes", "idli", "moderate", "Steamed rice-lentil cakes; low GI but portion matters."],
    ["diabetes", "dosa", "moderate", "Fermented rice-lentil, watch portion and oil."],
    ["diabetes", "upma", "moderate", "Semolina dish; low fat, portion control."],
    ["diabetes", "paneer", "recommend", "Low carb, protein rich, controls hunger."],
    ["diabetes", "chicken", "recommend", "Lean protein helps regulate blood sugar."],
    ["diabetes", "fish", "recommend", "Omega-3 improves insulin sensitivity."],
    ["diabetes", "egg", "recommend", "Low carb protein source."],
    ["diabetes", "milk", "moderate", "Opt for low-fat milk; can raise insulin."],
    ["diabetes", "curd", "recommend", "Low GI, protein rich, supports gut health."],
    ["diabetes", "cheese", "avoid", "High fat may worsen insulin resistance."],
    ["diabetes", "lentils", "recommend", "Fiber slows glucose release."],
    ["diabetes", "chickpeas", "recommend", "Low GI protein + fiber."],
    ["diabetes", "kidney beans", "recommend", "High protein and fiber, low GI."],
    ["diabetes", "moong dal", "recommend", "Light, high protein, stabilizes sugar."],
    ["diabetes", "nuts", "recommend", "Healthy fats improve insulin sensitivity."],
    ["diabetes", "almonds", "recommend", "Good for heart and glucose control."],
    ["diabetes", "walnuts", "recommend", "Omega-3 supports insulin function."],
    ["diabetes", "green tea", "recommend", "Polyphenols improve glucose metabolism."],
    ["diabetes", "black coffee", "moderate", "Unsweetened; may boost metabolism."],
    ["diabetes", "carrot", "recommend", "Low GI, rich in fiber and vitamins."],
    ["diabetes", "cabbage", "recommend", "Low calorie, stabilizes blood sugar."],
    ["diabetes", "broccoli", "recommend", "Antioxidants support glucose control."],
    ["diabetes", "tomato", "recommend", "Low sugar, antioxidant lycopene helps."],
    ["diabetes", "bell pepper", "recommend", "Rich in fiber and vitamin C."],
    ["diabetes", "spinach", "recommend", "Low carb, magnesium-rich, good for glucose."],
    ["diabetes", "cucumber", "recommend", "Low calorie, hydrating, stabilizes sugar."],
    ["diabetes", "methi leaves", "recommend", "Helps lower blood sugar naturally."],
    ["diabetes", "fenugreek seeds", "recommend", "Helps control glucose levels."],
    ["diabetes", "okra", "recommend", "Low GI, fiber-rich, stabilizes sugar."],
    ["diabetes", "pumpkin", "moderate", "Contains carbs, portion control needed."],

    # --- Obesity ---
    ["obesity", "banana", "avoid", "High sugar and calorie dense."],
    ["obesity", "apple", "recommend", "Low calorie, high fiber, aids weight loss."],
    ["obesity", "rice", "avoid", "Calorie dense, promotes fat gain."],
    ["obesity", "brown rice", "recommend", "Better fiber profile, more filling."],
    ["obesity", "wheat", "recommend", "Whole wheat increases satiety."],
    ["obesity", "oats", "recommend", "Fiber rich, keeps you full longer."],
    ["obesity", "spinach", "recommend", "Nutrient dense, low calorie."],
    ["obesity", "broccoli", "recommend", "Fiber supports fat metabolism."],
    ["obesity", "cabbage", "recommend", "Low calorie, aids fullness."],
    ["obesity", "tomato", "recommend", "Antioxidants + low calorie."],
    ["obesity", "fish", "recommend", "Lean protein, builds muscle."],
    ["obesity", "chicken", "recommend", "Protein source, helps lean mass."],
    ["obesity", "egg", "recommend", "Keeps you fuller longer."],
    ["obesity", "milk", "avoid", "High calorie if full cream."],
    ["obesity", "paneer", "recommend", "Protein rich, filling."],
    ["obesity", "cheese", "avoid", "High fat, calorie dense."],
    ["obesity", "lentils", "recommend", "Plant protein, low calorie."],
    ["obesity", "chickpeas", "recommend", "Protein + fiber, good satiety."],
    ["obesity", "nuts", "recommend", "Healthy fats, portion control needed."],
    ["obesity", "green tea", "recommend", "Boosts metabolism."],

    ["obesity", "banana", "avoid", "High sugar and calorie dense."],
    ["obesity", "apple", "recommend", "Low calorie, high fiber, aids weight loss."],
    ["obesity", "mango", "avoid", "High sugar, promotes weight gain."],
    ["obesity", "papaya", "recommend", "Low calorie, high fiber, helps digestion."],
    ["obesity", "guava", "recommend", "Rich in fiber, keeps you full longer."],
    ["obesity", "orange", "recommend", "Vitamin C rich, low calorie fruit."],
    ["obesity", "watermelon", "moderate", "Hydrating but high sugar; portion control."],
    ["obesity", "rice", "avoid", "Refined carbs, high calories, promotes fat gain."],
    ["obesity", "brown rice", "recommend", "Better fiber profile, more filling."],
    ["obesity", "roti", "recommend", "Whole wheat, low GI, helps satiety."],
    ["obesity", "jowar roti", "recommend", "Low GI millet, keeps full longer."],
    ["obesity", "bajra roti", "recommend", "High fiber, good for satiety and digestion."],
    ["obesity", "poha", "moderate", "Low fat breakfast; portion control needed."],
    ["obesity", "idli", "recommend", "Steamed, low fat, good for breakfast."],
    ["obesity", "dosa", "moderate", "Watch oil content; fermented and light."],
    ["obesity", "upma", "recommend", "Low fat, filling, fiber-rich."],
    ["obesity", "paneer", "moderate", "Protein rich but high in fat; portion control."],
    ["obesity", "chicken", "recommend", "Lean protein, supports lean mass."],
    ["obesity", "fish", "recommend", "Lean protein, omega-3 promotes fat metabolism."],
    ["obesity", "egg", "recommend", "Keeps you full longer, good protein source."],
    ["obesity", "milk", "moderate", "Low-fat milk preferred; high-fat milk increases calories."],
    ["obesity", "curd", "recommend", "Low-fat, probiotic, helps digestion."],
    ["obesity", "cheese", "avoid", "High fat and calorie dense."],
    ["obesity", "lentils", "recommend", "Plant protein, fiber keeps full longer."],
    ["obesity", "chickpeas", "recommend", "Protein + fiber support satiety."],
    ["obesity", "moong dal", "recommend", "Light, high protein, low calorie."],
    ["obesity", "kidney beans", "recommend", "Fiber and protein rich, helps fullness."],
    ["obesity", "nuts", "moderate", "High calories; portion control needed."],
    ["obesity", "almonds", "moderate", "Healthy fats but watch quantity."],
    ["obesity", "walnuts", "moderate", "Omega-3 supports metabolism; portion control."],
    ["obesity", "green tea", "recommend", "Boosts metabolism and reduces fat storage."],
    ["obesity", "black coffee", "recommend", "Unsweetened, supports metabolism."],
    ["obesity", "carrot", "recommend", "Low calorie, fiber-rich vegetable."],
    ["obesity", "cabbage", "recommend", "Low calorie, high fiber, aids fullness."],
    ["obesity", "broccoli", "recommend", "Low calorie, antioxidant-rich."],
    ["obesity", "tomato", "recommend", "Low calorie, antioxidants support metabolism."],
    ["obesity", "bell pepper", "recommend", "Low calorie, vitamin rich."],
    ["obesity", "spinach", "recommend", "Low calorie, nutrient dense."],
    ["obesity", "cucumber", "recommend", "Hydrating, low calorie."],
    ["obesity", "methi leaves", "recommend", "Fiber-rich, aids weight management."],
    ["obesity", "okra", "recommend", "Low calorie, fiber-rich, helps fullness."],
    ["obesity", "pumpkin", "recommend", "Low calorie, helps satiety."],


    # --- Hypertension ---
    ["hypertension", "banana", "recommend", "Potassium lowers blood pressure."],
    ["hypertension", "apple", "recommend", "Fiber supports heart health."],
    ["hypertension", "rice", "avoid", "Refined carbs increase BP risk."],
    ["hypertension", "brown rice", "recommend", "Fiber supports vascular health."],
    ["hypertension", "wheat", "recommend", "Whole wheat supports arteries."],
    ["hypertension", "oats", "recommend", "Lowers cholesterol and BP."],
    ["hypertension", "spinach", "recommend", "Rich in nitrates for vessel health."],
    ["hypertension", "broccoli", "recommend", "Magnesium lowers BP."],
    ["hypertension", "cabbage", "recommend", "Low sodium, heart friendly."],
    ["hypertension", "tomato", "recommend", "Potassium + lycopene support BP."],
    ["hypertension", "fish", "recommend", "Omega-3 improves heart health."],
    ["hypertension", "chicken", "recommend", "Lean protein, low sodium."],
    ["hypertension", "egg", "moderate", "Limit due to cholesterol content."],
    ["hypertension", "milk", "avoid", "Full-fat milk raises cholesterol."],
    ["hypertension", "paneer", "moderate", "Watch sodium and fat intake."],
    ["hypertension", "cheese", "avoid", "High sodium worsens BP."],
    ["hypertension", "lentils", "recommend", "Protein source, good for BP."],
    ["hypertension", "chickpeas", "recommend", "Rich in potassium and magnesium."],
    ["hypertension", "nuts", "recommend", "Healthy fats relax vessels."],
    ["hypertension", "green tea", "recommend", "Antioxidants support arteries."],

    ["hypertension", "banana", "recommend", "Potassium lowers blood pressure."],
    ["hypertension", "apple", "recommend", "Fiber supports heart and vessel health."],
    ["hypertension", "orange", "recommend", "Rich in vitamin C and potassium."],
    ["hypertension", "pomegranate", "recommend", "Antioxidants help lower BP."],
    ["hypertension", "watermelon", "recommend", "Hydrating, contains L-citrulline to relax vessels."],
    ["hypertension", "guava", "recommend", "High potassium, supports BP control."],
    ["hypertension", "mango", "moderate", "High sugar, consume in moderation."],
    ["hypertension", "rice", "avoid", "Refined carbs increase BP risk."],
    ["hypertension", "brown rice", "recommend", "Fiber-rich, supports vascular health."],
    ["hypertension", "roti", "recommend", "Whole wheat supports blood pressure control."],
    ["hypertension", "jowar roti", "recommend", "High fiber, low sodium, supports heart health."],
    ["hypertension", "bajra roti", "recommend", "Millet is high fiber, low sodium."],
    ["hypertension", "poha", "moderate", "Low sodium; avoid adding excess salt."],
    ["hypertension", "idli", "recommend", "Steamed, low sodium, heart-friendly."],
    ["hypertension", "dosa", "moderate", "Watch oil and salt; fermented and light."],
    ["hypertension", "upma", "recommend", "Low sodium, fiber-rich breakfast."],
    ["hypertension", "spinach", "recommend", "Rich in nitrates, helps relax vessels."],
    ["hypertension", "broccoli", "recommend", "Magnesium lowers blood pressure."],
    ["hypertension", "cabbage", "recommend", "Low sodium, fiber-rich vegetable."],
    ["hypertension", "tomato", "recommend", "Potassium + lycopene support BP control."],
    ["hypertension", "carrot", "recommend", "Low sodium, antioxidant-rich."],
    ["hypertension", "bell pepper", "recommend", "Rich in vitamin C, low sodium."],
    ["hypertension", "okra", "recommend", "Low sodium, fiber supports BP."],
    ["hypertension", "pumpkin", "recommend", "Low calorie, supports vascular health."],
    ["hypertension", "fenugreek leaves", "recommend", "High fiber, supports heart health."],
    ["hypertension", "fish", "recommend", "Omega-3 fatty acids improve heart health."],
    ["hypertension", "chicken", "recommend", "Lean protein, low sodium."],
    ["hypertension", "egg", "moderate", "Limit yolks due to cholesterol content."],
    ["hypertension", "milk", "moderate", "Low-fat preferred; high-fat raises BP risk."],
    ["hypertension", "curd", "recommend", "Low-fat, probiotic, supports BP."],
    ["hypertension", "paneer", "moderate", "Use in moderation; watch fat content."],
    ["hypertension", "cheese", "avoid", "High sodium worsens blood pressure."],
    ["hypertension", "lentils", "recommend", "Fiber-rich, supports heart and BP."],
    ["hypertension", "chickpeas", "recommend", "High potassium and magnesium."],
    ["hypertension", "moong dal", "recommend", "Light, high protein, low sodium."],
    ["hypertension", "kidney beans", "recommend", "Fiber and protein, supports BP."],
    ["hypertension", "nuts", "moderate", "Healthy fats; avoid excess salt or sugar."],
    ["hypertension", "almonds", "moderate", "Support heart health, watch quantity."],
    ["hypertension", "walnuts", "moderate", "Omega-3 supports BP control."],
    ["hypertension", "green tea", "recommend", "Antioxidants improve vascular function."],
    ["hypertension", "black coffee", "moderate", "Unsweetened only; too much caffeine can raise BP."],





    # --- Thyroid ---
    ["thyroid", "banana", "moderate", "Safe but watch portion if weight gain risk."],
    ["thyroid", "apple", "recommend", "Supports metabolism, iodine safe."],
    ["thyroid", "rice", "avoid", "Excess carbs worsen metabolism."],
    ["thyroid", "brown rice", "recommend", "Better for metabolism than white rice."],
    ["thyroid", "wheat", "moderate", "Whole wheat okay, refined is bad."],
    ["thyroid", "oats", "recommend", "Fiber supports digestion and hormones."],
    ["thyroid", "spinach", "avoid", "Goitrogenic, limit in hypothyroidism."],
    ["thyroid", "broccoli", "avoid", "Goitrogenic vegetables worsen thyroid."],
    ["thyroid", "cabbage", "avoid", "Interferes with thyroid hormone production."],
    ["thyroid", "tomato", "recommend", "Rich in antioxidants, thyroid friendly."],
    ["thyroid", "fish", "recommend", "Rich in iodine and omega-3, good for thyroid."],
    ["thyroid", "chicken", "recommend", "Protein rich, boosts metabolism."],
    ["thyroid", "egg", "recommend", "Iodine and selenium support thyroid."],
    ["thyroid", "milk", "recommend", "Iodine source, supports hormone production."],
    ["thyroid", "paneer", "recommend", "Protein + iodine rich."],
    ["thyroid", "cheese", "recommend", "Contains iodine, supports thyroid."],
    ["thyroid", "lentils", "recommend", "Plant protein, safe for thyroid."],
    ["thyroid", "chickpeas", "recommend", "Good for energy and metabolism."],
    ["thyroid", "nuts", "recommend", "Selenium and zinc support thyroid."],
    ["thyroid", "green tea", "recommend", "Boosts metabolism, safe."],

    ["thyroid", "banana", "moderate", "Safe, but monitor portion for weight gain."],
    ["thyroid", "apple", "recommend", "Supports metabolism, safe for thyroid."],
    ["thyroid", "orange", "recommend", "Vitamin C improves iron absorption, safe."],
    ["thyroid", "pomegranate", "recommend", "Antioxidants support thyroid function."],
    ["thyroid", "guava", "recommend", "Rich in vitamin C and fiber, safe for thyroid."],
    ["thyroid", "mango", "moderate", "High sugar, consume in moderation."],
    ["thyroid", "rice", "moderate", "Prefer brown rice; avoid excess white rice."],
    ["thyroid", "brown rice", "recommend", "Better fiber content, stable energy release."],
    ["thyroid", "roti", "moderate", "Whole wheat preferred; avoid refined flour."],
    ["thyroid", "jowar roti", "recommend", "Millet supports metabolism."],
    ["thyroid", "bajra roti", "recommend", "High fiber, low glycemic, good for thyroid."],
    ["thyroid", "poha", "moderate", "Light meal, watch added salt."],
    ["thyroid", "idli", "recommend", "Steamed, low-fat, thyroid-friendly."],
    ["thyroid", "dosa", "moderate", "Fermented, low-fat, watch oil."],
    ["thyroid", "upma", "recommend", "Low sodium, fiber-rich breakfast."],
    ["thyroid", "spinach", "avoid", "Goitrogenic; limit if hypothyroid."],
    ["thyroid", "broccoli", "avoid", "Raw forms may interfere with thyroid hormones."],
    ["thyroid", "cabbage", "avoid", "Goitrogenic; consume cooked if needed."],
    ["thyroid", "tomato", "recommend", "Rich in antioxidants, thyroid-friendly."],
    ["thyroid", "carrot", "recommend", "Supports metabolism, safe for thyroid."],
    ["thyroid", "bell pepper", "recommend", "Vitamin C rich, supports thyroid health."],
    ["thyroid", "okra", "recommend", "Low-calorie, safe for thyroid."],
    ["thyroid", "pumpkin", "recommend", "Fiber-rich, aids metabolism."],
    ["thyroid", "fenugreek leaves", "recommend", "Supports digestion and metabolism."],
    ["thyroid", "fish", "recommend", "Rich in iodine and omega-3, supports thyroid."],
    ["thyroid", "chicken", "recommend", "Lean protein boosts metabolism."],
    ["thyroid", "egg", "recommend", "Iodine and selenium support thyroid function."],
    ["thyroid", "milk", "recommend", "Iodine source, supports hormone production."],
    ["thyroid", "curd", "recommend", "Probiotic and iodine rich, supports thyroid."],
    ["thyroid", "paneer", "recommend", "Protein and iodine-rich, safe in moderation."],
    ["thyroid", "cheese", "moderate", "Iodine present, avoid high-fat cheese."],
    ["thyroid", "lentils", "recommend", "Plant protein, safe for thyroid."],
    ["thyroid", "chickpeas", "recommend", "Fiber and protein support metabolism."],
    ["thyroid", "moong dal", "recommend", "Light, safe protein source."],
    ["thyroid", "kidney beans", "moderate", "Cook well, avoid excess."],
    ["thyroid", "nuts", "recommend", "Selenium and healthy fats support thyroid."],
    ["thyroid", "almonds", "recommend", "Good for metabolism, portion control needed."],
    ["thyroid", "walnuts", "recommend", "Omega-3 supports thyroid and heart."],
    ["thyroid", "green tea", "recommend", "Boosts metabolism, safe for thyroid."],
    ["thyroid", "black coffee", "moderate", "Moderate caffeine is fine; avoid sugar."],
    ["thyroid", "ginger", "recommend", "Supports digestion and metabolism."],
    ["thyroid", "turmeric", "recommend", "Anti-inflammatory, thyroid-friendly."],
    ["thyroid", "garlic", "recommend", "Supports metabolism and heart health."],



    # --- PCOS ---
    ["pcos", "banana", "avoid", "High sugar, worsens insulin resistance."],
    ["pcos", "apple", "recommend", "Low GI, fiber stabilizes sugar."],
    ["pcos", "rice", "avoid", "Refined carbs worsen PCOS symptoms."],
    ["pcos", "brown rice", "recommend", "Better than white rice for sugar control."],
    ["pcos", "wheat", "moderate", "Whole wheat better, avoid refined."],
    ["pcos", "oats", "recommend", "Fiber rich, improves insulin sensitivity."],
    ["pcos", "spinach", "recommend", "Iron + folate support hormone balance."],
    ["pcos", "broccoli", "recommend", "Antioxidants improve insulin resistance."],
    ["pcos", "cabbage", "recommend", "Fiber and low calorie, supports PCOS diet."],
    ["pcos", "tomato", "recommend", "Antioxidants support hormone health."],
    ["pcos", "fish", "recommend", "Omega-3 reduces inflammation in PCOS."],
    ["pcos", "chicken", "recommend", "Lean protein supports hormone balance."],
    ["pcos", "egg", "recommend", "Protein source, safe in PCOS."],
    ["pcos", "milk", "avoid", "Dairy may worsen hormonal imbalance."],
    ["pcos", "paneer", "avoid", "Dairy protein can aggravate PCOS."],
    ["pcos", "cheese", "avoid", "High fat dairy worsens PCOS."],
    ["pcos", "lentils", "recommend", "Plant protein improves insulin sensitivity."],
    ["pcos", "chickpeas", "recommend", "Fiber + protein stabilize blood sugar."],
    ["pcos", "nuts", "recommend", "Healthy fats improve hormone balance."],
    ["pcos", "green tea", "recommend", "Reduces androgen levels, helps PCOS."],

    ["pcos", "banana", "avoid", "High sugar content may worsen insulin resistance."],
    ["pcos", "apple", "recommend", "Low GI, high fiber stabilizes blood sugar."],
    ["pcos", "orange", "recommend", "Rich in vitamin C, low GI fruit."],
    ["pcos", "pomegranate", "recommend", "Antioxidants support hormone balance."],
    ["pcos", "guava", "recommend", "High fiber, low sugar, helps insulin control."],
    ["pcos", "mango", "moderate", "High sugar; limit portion size."],
    ["pcos", "rice", "avoid", "Refined carbs spike blood sugar."],
    ["pcos", "brown rice", "recommend", "Low GI, keeps glucose stable."],
    ["pcos", "roti", "recommend", "Whole wheat, high fiber, better than refined flour."],
    ["pcos", "jowar roti", "recommend", "Low glycemic, supports insulin sensitivity."],
    ["pcos", "bajra roti", "recommend", "High fiber, promotes satiety."],
    ["pcos", "poha", "moderate", "Light meal, avoid excess oil and sugar."],
    ["pcos", "idli", "recommend", "Low fat, steamed, suitable breakfast."],
    ["pcos", "dosa", "moderate", "Fermented, but avoid excess oil."],
    ["pcos", "upma", "recommend", "High fiber and low fat, stabilizes glucose."],
    ["pcos", "spinach", "recommend", "Iron and fiber support hormonal health."],
    ["pcos", "broccoli", "recommend", "Antioxidants improve insulin sensitivity."],
    ["pcos", "cabbage", "recommend", "High fiber, low calorie, safe for PCOS."],
    ["pcos", "tomato", "recommend", "Antioxidants support hormone balance."],
    ["pcos", "carrot", "recommend", "Supports metabolism and vitamin A intake."],
    ["pcos", "capsicum", "recommend", "Low GI, rich in vitamin C."],
    ["pcos", "okra", "recommend", "Low calorie, fiber-rich vegetable."],
    ["pcos", "pumpkin", "recommend", "Supports satiety and fiber intake."],
    ["pcos", "fenugreek leaves", "recommend", "Helps control blood sugar."],
    ["pcos", "fish", "recommend", "Omega-3 reduces inflammation."],
    ["pcos", "chicken", "recommend", "Lean protein helps hormone balance."],
    ["pcos", "egg", "recommend", "Protein source, stabilizes blood sugar."],
    ["pcos", "milk", "moderate", "Prefer low-fat milk, avoid excess."],
    ["pcos", "curd", "recommend", "Probiotics support gut and hormone balance."],
    ["pcos", "paneer", "moderate", "Protein rich, avoid high-fat varieties."],
    ["pcos", "cheese", "avoid", "High fat and calories, may worsen PCOS."],
    ["pcos", "lentils", "recommend", "Plant protein supports glucose control."],
    ["pcos", "chickpeas", "recommend", "Low GI protein + fiber."],
    ["pcos", "moong dal", "recommend", "Light, protein-rich, good for insulin control."],
    ["pcos", "kidney beans", "recommend", "High protein, fiber-rich, low GI."],
    ["pcos", "nuts", "recommend", "Healthy fats improve hormone balance."],
    ["pcos", "almonds", "recommend", "Supports satiety, healthy fats for hormones."],
    ["pcos", "walnuts", "recommend", "Omega-3 helps reduce androgen levels."],
    ["pcos", "flaxseeds", "recommend", "Supports hormone balance and fiber intake."],
    ["pcos", "chia seeds", "recommend", "Omega-3 and fiber-rich, stabilizes glucose."],
    ["pcos", "green tea", "recommend", "Reduces insulin resistance and androgen levels."],
    ["pcos", "ginger", "recommend", "Anti-inflammatory, supports metabolism."],
    ["pcos", "turmeric", "recommend", "Helps reduce inflammation."],
    ["pcos", "garlic", "recommend", "Supports metabolism and hormone balance."],



    # --- Kidney Disease ---
    ["kidney disease", "banana", "avoid", "High potassium stresses kidneys."],
    ["kidney disease", "apple", "recommend", "Low potassium fruit, safe for kidneys."],
    ["kidney disease", "rice", "recommend", "Low potassium, kidney safe carb."],
    ["kidney disease", "brown rice", "avoid", "High phosphorus and potassium."],
    ["kidney disease", "wheat", "avoid", "Whole wheat high in phosphorus."],
    ["kidney disease", "oats", "avoid", "Phosphorus-rich, bad for kidney patients."],
    ["kidney disease", "spinach", "avoid", "High potassium, strain on kidneys."],
    ["kidney disease", "broccoli", "avoid", "High potassium and phosphorus."],
    ["kidney disease", "cabbage", "recommend", "Low potassium, kidney friendly."],
    ["kidney disease", "tomato", "avoid", "High potassium, dangerous in CKD."],
    ["kidney disease", "fish", "moderate", "Protein needed but limit phosphorus."],
    ["kidney disease", "chicken", "moderate", "Protein okay but portion control."],
    ["kidney disease", "egg", "moderate", "Protein source, limit yolks."],
    ["kidney disease", "milk", "avoid", "High phosphorus, not kidney safe."],
    ["kidney disease", "paneer", "avoid", "High phosphorus, harmful in CKD."],
    ["kidney disease", "cheese", "avoid", "Very high sodium + phosphorus."],
    ["kidney disease", "lentils", "avoid", "High potassium + phosphorus."],
    ["kidney disease", "chickpeas", "avoid", "Potassium and phosphorus rich."],
    ["kidney disease", "nuts", "avoid", "Too high potassium, bad for kidneys."],
    ["kidney disease", "green tea", "moderate", "Safe but limit fluid intake."],

    ["kidney disease", "banana", "avoid", "High potassium; may strain kidneys."],
    ["kidney disease", "apple", "recommend", "Low potassium fruit, safe for kidneys."],
    ["kidney disease", "orange", "moderate", "Moderate potassium; limit portion."],
    ["kidney disease", "pomegranate", "recommend", "Low potassium, antioxidant-rich."],
    ["kidney disease", "guava", "moderate", "Contains potassium; eat in small amounts."],
    ["kidney disease", "mango", "avoid", "High potassium and sugar; not safe in CKD."],
    ["kidney disease", "rice", "recommend", "Low potassium, kidney-friendly carbohydrate."],
    ["kidney disease", "brown rice", "moderate", "Contains more phosphorus; portion control."],
    ["kidney disease", "roti", "recommend", "Whole wheat in moderate quantity is fine."],
    ["kidney disease", "jowar roti", "recommend", "Low phosphorus, safe for CKD."],
    ["kidney disease", "bajra roti", "recommend", "Good alternative with low potassium."],
    ["kidney disease", "poha", "moderate", "Watch portion; low potassium but may contain salt."],
    ["kidney disease", "idli", "recommend", "Steamed, low potassium, safe for kidneys."],
    ["kidney disease", "dosa", "moderate", "Limit oil; moderate potassium content."],
    ["kidney disease", "upma", "recommend", "Low potassium and moderate sodium if made without excess salt."],
    ["kidney disease", "spinach", "avoid", "Very high in potassium and oxalates."],
    ["kidney disease", "broccoli", "moderate", "Contains potassium; portion control advised."],
    ["kidney disease", "cabbage", "recommend", "Low potassium, safe vegetable."],
    ["kidney disease", "tomato", "avoid", "High potassium, limit in CKD."],
    ["kidney disease", "carrot", "moderate", "Contains potassium; eat in small amounts."],
    ["kidney disease", "capsicum", "recommend", "Low potassium, kidney-friendly."],
    ["kidney disease", "okra", "moderate", "Contains potassium; limit quantity."],
    ["kidney disease", "pumpkin", "recommend", "Low potassium, safe for CKD."],
    ["kidney disease", "fenugreek leaves", "recommend", "Low potassium, safe herb."],
    ["kidney disease", "fish", "moderate", "Lean protein; limit portion due to phosphorus."],
    ["kidney disease", "chicken", "moderate", "Lean protein; watch phosphorus intake."],
    ["kidney disease", "egg", "recommend", "Protein source; safe if consumed in moderation."],
    ["kidney disease", "milk", "avoid", "High potassium and phosphorus; avoid full-fat."],
    ["kidney disease", "curd", "moderate", "Protein source; watch phosphorus."],
    ["kidney disease", "paneer", "avoid", "High phosphorus and potassium; not safe in CKD."],
    ["kidney disease", "cheese", "avoid", "High sodium, phosphorus, potassium; unsafe."],
    ["kidney disease", "lentils", "avoid", "High potassium and phosphorus; limit intake."],
    ["kidney disease", "chickpeas", "avoid", "Rich in potassium and phosphorus."],
    ["kidney disease", "moong dal", "recommend", "Low potassium, good protein source."],
    ["kidney disease", "kidney beans", "avoid", "High potassium and phosphorus; dangerous in CKD."],
    ["kidney disease", "nuts", "avoid", "High potassium; restrict intake."],
    ["kidney disease", "almonds", "avoid", "High potassium and phosphorus; avoid."],
    ["kidney disease", "walnuts", "moderate", "Limit quantity; moderate potassium."],
    ["kidney disease", "flaxseeds", "recommend", "Good fats, low potassium if portion controlled."],
    ["kidney disease", "chia seeds", "moderate", "High fiber but watch potassium and phosphorus."],
    ["kidney disease", "green tea", "recommend", "Low potassium, kidney-friendly beverage."],
    ["kidney disease", "ginger", "recommend", "Supports digestion, safe for CKD."],
    ["kidney disease", "turmeric", "recommend", "Anti-inflammatory, safe in moderation."],
    ["kidney disease", "garlic", "recommend", "Flavor enhancer, safe for CKD if no excess salt."],



    # --- Heart Disease ---
    ["heart disease","banana","recommend","Potassium supports heart health."],
    ["heart disease","apple","recommend","Fiber lowers cholesterol."],
    ["heart disease","rice","avoid","Refined carbs worsen heart risk."],
    ["heart disease","brown rice","recommend","Fiber improves cholesterol levels."],
    ["heart disease","wheat","recommend","Whole grains lower LDL."],
    ["heart disease","oats","recommend","Beta-glucan lowers cholesterol."],
    ["heart disease","spinach","recommend","Nitrates improve vascular health."],
    ["heart disease","broccoli","recommend","Antioxidants protect the heart."],
    ["heart disease","cabbage","recommend","Supports cholesterol control."],
    ["heart disease","tomato","recommend","Lycopene reduces heart risk."],
    ["heart disease","fish","recommend","Omega-3 lowers triglycerides."],
    ["heart disease","chicken","recommend","Lean protein, safe for heart."],
    ["heart disease","egg","moderate","Protein source but limit yolks."],
    ["heart disease","milk","avoid","Full-fat milk worsens cholesterol."],
    ["heart disease","paneer","moderate","Limit due to saturated fat."],
    ["heart disease","cheese","avoid","High sodium and fat worsen heart risk."],
    ["heart disease","lentils","recommend","Plant protein lowers risk."],
    ["heart disease","chickpeas","recommend","Fiber and protein heart-friendly."],
    ["heart disease","nuts","recommend","Omega-3 improves heart function."],
    ["heart disease","green tea","recommend","Antioxidants reduce heart disease."],

    ["heart disease", "banana", "recommend", "Potassium supports heart and lowers BP."],
    ["heart disease", "apple", "recommend", "Fiber lowers cholesterol; antioxidant-rich."],
    ["heart disease", "orange", "recommend", "Vitamin C, low fat, good for heart."],
    ["heart disease", "pomegranate", "recommend", "Antioxidants protect blood vessels."],
    ["heart disease", "guava", "recommend", "Vitamin C and fiber; heart-friendly."],
    ["heart disease", "mango", "moderate", "Moderate sugar; eat in portion control."],
    ["heart disease", "rice", "moderate", "Prefer brown rice; white rice in small amounts."],
    ["heart disease", "brown rice", "recommend", "Fiber-rich, lowers cholesterol."],
    ["heart disease", "roti", "recommend", "Whole wheat, moderate portion is safe."],
    ["heart disease", "jowar roti", "recommend", "Low GI, heart-friendly alternative."],
    ["heart disease", "bajra roti", "recommend", "High fiber, good for cholesterol control."],
    ["heart disease", "poha", "moderate", "Limit added oil and salt."],
    ["heart disease", "idli", "recommend", "Steamed, low fat, easy on heart."],
    ["heart disease", "dosa", "moderate", "Limit oil; otherwise heart-friendly."],
    ["heart disease", "upma", "recommend", "Low fat, good fiber; watch salt."],
    ["heart disease", "spinach", "recommend", "Rich in nitrates; supports blood vessel health."],
    ["heart disease", "broccoli", "recommend", "Antioxidants reduce heart disease risk."],
    ["heart disease", "cabbage", "recommend", "Low calorie, supports cholesterol control."],
    ["heart disease", "tomato", "recommend", "Lycopene reduces LDL cholesterol."],
    ["heart disease", "carrot", "recommend", "Beta-carotene and fiber support heart."],
    ["heart disease", "capsicum", "recommend", "Rich in antioxidants; heart-friendly."],
    ["heart disease", "okra", "recommend", "Soluble fiber supports cholesterol control."],
    ["heart disease", "pumpkin", "recommend", "Low calorie, supports heart health."],
    ["heart disease", "fenugreek leaves", "recommend", "Helps manage blood sugar and cholesterol."],
    ["heart disease", "fish", "recommend", "Omega-3 reduces triglycerides and inflammation."],
    ["heart disease", "chicken", "moderate", "Lean protein; avoid fried forms."],
    ["heart disease", "egg", "moderate", "Egg whites safe; limit yolks."],
    ["heart disease", "milk", "moderate", "Low-fat milk only; avoid full-fat."],
    ["heart disease", "curd", "recommend", "Low-fat, probiotic-rich; good for heart."],
    ["heart disease", "paneer", "moderate", "Low-fat paneer; avoid high-fat versions."],
    ["heart disease", "cheese", "avoid", "High saturated fat and sodium; not safe."],
    ["heart disease", "lentils", "recommend", "Plant protein, helps manage cholesterol."],
    ["heart disease", "chickpeas", "recommend", "Fiber-rich, supports heart health."],
    ["heart disease", "moong dal", "recommend", "Low-fat protein source; heart-friendly."],
    ["heart disease", "kidney beans", "moderate", "Good protein; watch portion and sodium."],
    ["heart disease", "nuts", "recommend", "Almonds, walnuts, healthy fats in moderation."],
    ["heart disease", "almonds", "recommend", "Omega-3 and fiber reduce cholesterol."],
    ["heart disease", "walnuts", "recommend", "Supports heart due to healthy fats."],
    ["heart disease", "flaxseeds", "recommend", "Omega-3 fatty acids; good for cholesterol."],
    ["heart disease", "chia seeds", "recommend", "Fiber and omega-3 support heart health."],
    ["heart disease", "green tea", "recommend", "Antioxidants reduce oxidative stress."],
    ["heart disease", "ginger", "recommend", "Anti-inflammatory; safe for heart."],
    ["heart disease", "turmeric", "recommend", "Curcumin reduces inflammation."],
    ["heart disease", "garlic", "recommend", "Lowers cholesterol; heart-friendly."],



    # --- Chronic Kidney Disease ---

    ["chronic kidney disease", "banana", "avoid", "High in potassium, can strain kidneys."],
    ["chronic kidney disease", "apple", "recommend", "Low potassium, safe for kidneys."],
    ["chronic kidney disease", "rice", "recommend", "Low potassium carb, kidney friendly."],
    ["chronic kidney disease", "brown rice", "moderate", "Better fiber but higher potassium than white rice."],
    ["chronic kidney disease", "oats", "moderate", "Good fiber but monitor potassium content."],
    ["chronic kidney disease", "spinach", "avoid", "Very high potassium and oxalates, harmful in CKD."],
    ["chronic kidney disease", "broccoli", "moderate", "Contains potassium; limit portion size."],
    ["chronic kidney disease", "cabbage", "recommend", "Low potassium, kidney friendly."],
    ["chronic kidney disease", "tomato", "avoid", "High potassium, not recommended."],
    ["chronic kidney disease", "fish", "moderate", "Protein is needed but avoid high phosphorus types."],
    ["chronic kidney disease", "chicken", "moderate", "Lean protein, portion control important."],
    ["chronic kidney disease", "egg", "recommend", "Good protein source, safe in moderation."],
    ["chronic kidney disease", "milk", "avoid", "High phosphorus and potassium, can harm kidneys."],
    ["chronic kidney disease", "paneer", "avoid", "High phosphorus content, not safe."],
    ["chronic kidney disease", "cheese", "avoid", "High sodium and phosphorus, avoid."],
    ["chronic kidney disease", "lentils", "moderate", "Protein source but high in potassium/phosphorus; limit portion."],
    ["chronic kidney disease", "chickpeas", "moderate", "Good protein, watch potassium content."],
    ["chronic kidney disease", "nuts", "avoid", "High potassium and phosphorus, harmful."],
    ["chronic kidney disease", "green tea", "recommend", "Safe beverage, supports hydration."],
    ["chronic kidney disease", "carrot", "recommend", "Low potassium, kidney friendly."],

    ["chronic kidney disease", "banana", "avoid", "High potassium; may strain kidneys."],
    ["chronic kidney disease", "apple", "recommend", "Low potassium, safe for kidneys."],
    ["chronic kidney disease", "orange", "moderate", "Contains potassium; limit portion."],
    ["chronic kidney disease", "pomegranate", "recommend", "Low potassium, antioxidant-rich."],
    ["chronic kidney disease", "guava", "moderate", "Contains potassium; watch portion."],
    ["chronic kidney disease", "mango", "moderate", "Limit due to potassium and sugar."],
    ["chronic kidney disease", "rice", "recommend", "Low potassium carb, safe choice."],
    ["chronic kidney disease", "brown rice", "moderate", "Higher phosphorus; eat in moderation."],
    ["chronic kidney disease", "roti", "recommend", "Whole wheat in small portion; safe."],
    ["chronic kidney disease", "jowar roti", "recommend", "Low potassium, heart-healthy."],
    ["chronic kidney disease", "bajra roti", "recommend", "Low potassium; good fiber source."],
    ["chronic kidney disease", "poha", "recommend", "Low potassium breakfast option."],
    ["chronic kidney disease", "idli", "recommend", "Low-potassium steamed dish; safe."],
    ["chronic kidney disease", "dosa", "moderate", "Limit oil and toppings."],
    ["chronic kidney disease", "upma", "recommend", "Low potassium; avoid excess salt."],
    ["chronic kidney disease", "spinach", "avoid", "High potassium and oxalates; not safe."],
    ["chronic kidney disease", "broccoli", "moderate", "Rich in potassium; portion control."],
    ["chronic kidney disease", "cabbage", "recommend", "Low potassium; safe for kidneys."],
    ["chronic kidney disease", "tomato", "moderate", "Contains potassium; limit intake."],
    ["chronic kidney disease", "carrot", "recommend", "Low potassium, kidney-friendly."],
    ["chronic kidney disease", "capsicum", "recommend", "Low potassium, safe vegetable."],
    ["chronic kidney disease", "okra", "moderate", "Contains potassium; limit portion."],
    ["chronic kidney disease", "pumpkin", "recommend", "Low potassium; supports kidney health."],
    ["chronic kidney disease", "fenugreek leaves", "recommend", "Safe leafy option, low potassium."],
    ["chronic kidney disease", "fish", "moderate", "Protein needed; choose low-phosphorus types."],
    ["chronic kidney disease", "chicken", "moderate", "Lean protein; control portion."],
    ["chronic kidney disease", "egg", "recommend", "Low potassium protein source; safe."],
    ["chronic kidney disease", "milk", "moderate", "Choose low-fat; high phosphorus in excess."],
    ["chronic kidney disease", "curd", "recommend", "Low-potassium and safe in moderation."],
    ["chronic kidney disease", "paneer", "moderate", "Protein-rich but high phosphorus; limit."],
    ["chronic kidney disease", "cheese", "avoid", "High sodium and phosphorus; not safe."],
    ["chronic kidney disease", "lentils", "moderate", "High potassium and phosphorus; limit intake."],
    ["chronic kidney disease", "chickpeas", "moderate", "High potassium; portion control needed."],
    ["chronic kidney disease", "moong dal", "recommend", "Low potassium, safe protein source."],
    ["chronic kidney disease", "kidney beans", "avoid", "High potassium and phosphorus; harmful."],
    ["chronic kidney disease", "nuts", "moderate", "High potassium and phosphorus; eat sparingly."],
    ["chronic kidney disease", "almonds", "moderate", "Small portion only; high phosphorus."],
    ["chronic kidney disease", "walnuts", "recommend", "Healthy fats; portion control important."],
    ["chronic kidney disease", "flaxseeds", "recommend", "Low potassium, good omega-3 source."],
    ["chronic kidney disease", "chia seeds", "recommend", "Low potassium, fiber-rich; safe."],
    ["chronic kidney disease", "green tea", "recommend", "Safe beverage; supports kidney health."],
    ["chronic kidney disease", "ginger", "recommend", "Low potassium, anti-inflammatory."],
    ["chronic kidney disease", "turmeric", "recommend", "Supports kidney health; safe."],
    ["chronic kidney disease", "garlic", "recommend", "Low potassium; good for kidneys."],


] # Added missing closing bracket

df = pd.DataFrame(data, columns=["disease", "food", "recommendation", "explanation"])
df.to_csv("food_data.csv", index=False)

print("✅ CSV created with", len(df), "rows")
print(df.head(20))
import pandas as pd
import spacy
from fuzzywuzzy import process

# Load CSV
df = pd.read_csv("food_data.csv")

# Get list of foods and diseases
foods_list = df['food'].unique().tolist()
diseases_list = df['disease'].unique().tolist()

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

print("✅ CSV loaded. Number of rows:", len(df))
print("Foods:", foods_list[:10])
print("Diseases:", diseases_list)
def free_chat_bot(user_input):
    user_input_lower = user_input.lower()

    # Detect food using fuzzy matching
    food_match = process.extractOne(user_input_lower, foods_list)
    food = food_match[0] if food_match[1] > 60 else None  # 60% threshold

    # Detect disease using fuzzy matching
    disease_match = process.extractOne(user_input_lower, diseases_list)
    disease = disease_match[0] if disease_match[1] > 60 else None

    # Lookup in CSV
    if food and disease:
        result = df[(df['food'] == food) & (df['disease'] == disease)]
        if not result.empty:
            rec = result.iloc[0]['recommendation']
            expl = result.iloc[0]['explanation']
            return f"{food.title()} ({rec}): {expl}"
        else:
            return "Sorry, no info available for this food and disease."
    else:
        missing = []
        if not food: missing.append("food")
        if not disease: missing.append("disease")
        return f"Couldn't identify: {', '.join(missing)}. Please mention them clearly."
while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]:
        break
    response = free_chat_bot(user_input)
    print("Bot:", response)
